<?php
$config = $this->config()->get('LOTS');
$allowRecreatePassword = $config->PasswordRecovery->enable;
$newPatronUrl = $config->NewPatron->url;
$enableNewPatron = $config->NewPatron->enable;
?>
<?php $loginMethod = $this->auth()->getManager()->getILSLoginMethod(); ?>
<?php if ('email' === $loginMethod): ?>
  <div class="form-group">
    <label class="control-label" for="login_<?=$this->escapeHtmlAttr($topClass)?>_username"><?=$this->transEsc('Email')?>:</label>
    <input type="text" name="username" id="login_<?=$this->escapeHtmlAttr($topClass)?>_username" value="<?=$this->escapeHtmlAttr($this->request->get('username'))?>" class="form-control"/>
  </div>
<?php else: ?>
  <div class="form-group">
    <label class="control-label" for="login_<?=$this->escapeHtmlAttr($topClass)?>_username"><?=$this->transEsc('Username')?>:</label>
    <input type="text" name="username" id="login_<?=$this->escapeHtmlAttr($topClass)?>_username" value="<?=$this->escapeHtmlAttr($this->request->get('username'))?>" class="form-control"/>
  </div>
  <div class="form-group">
    <label class="control-label" for="login_<?=$this->escapeHtmlAttr($topClass)?>_password"><?=$this->transEsc('Password')?>:</label>
    <input type="password" name="password" id="login_<?=$this->escapeHtmlAttr($topClass)?>_password" class="form-control"/>
  </div>
<!-- Fixed for WCAG compliance - LOBININTEG-12 -->
<?php if ($allowRecreatePassword == 1) {?>
<div class="forgot_pin_code">
    <p class="control-label">
        <a href="<?=$this->url('home') ?>ForgotPassword/"><?=$this->transEsc('Forgot login')?></a>
    </p>
</div>
<?php } ?>
<?php if (isset($newPatronUrl) && $enableNewPatron) {?>
<div class="new_patron_url">
    <p class="control-label">
        <a href="<?=$newPatronUrl?>"><?=$this->transEsc('Create new patron')?></a>
    </p>
</div>
<?php } ?>
<?php endif; ?>
