<!-- START ./Auth/ILS/loginfields.phtml -->

<?php
  $config = $this->config()->get('LOTS');
  $allowRecreatePassword = $config->PasswordRecovery->enable;
?>



<?php $loginMethod = $this->auth()->getManager()->getILSLoginMethod(); ?>
<?php if ('email' === $loginMethod): ?>
  <div class="form-group">
    <label class="control-label" for="login_<?=$this->escapeHtmlAttr($topClass)?>_username"><?=$this->transEsc('Email')?>:</label>
    <input type="text" name="username" id="login_<?=$this->escapeHtmlAttr($topClass)?>_username" value="<?=$this->escapeHtmlAttr($this->request->get('username'))?>" class="form-control"/>
  </div>
<?php else: ?>
  <div class="form-group">
    <label class="control-label" for="login_<?=$this->escapeHtmlAttr($topClass)?>_username"><?=$this->transEsc('Username')?>:</label>
    <input type="text" name="username" id="login_<?=$this->escapeHtmlAttr($topClass)?>_username" value="<?=$this->escapeHtmlAttr($this->request->get('username'))?>" class="form-control"/>
  </div>
  <div class="form-group">
    <label class="control-label" for="login_<?=$this->escapeHtmlAttr($topClass)?>_password"><?=$this->transEsc('Password')?>:</label>
    <input type="password" name="password" id="login_<?=$this->escapeHtmlAttr($topClass)?>_password" class="form-control"/>
  </div>



<!-- Added for LOTS LOBININTEG-12 -->
<?php if ($allowRecreatePassword == 1) {?>
    <label class="control-label" for="login_<?=$this->escapeHtmlAttr($topClass)?>_forgot"><a href="<?=$this->url('home') ?>ForgotPassword/" ><?=$this->transEsc('Forgot login')?></a></label>
<?php } ?>

<?php endif; ?>
<!-- STOP ./Auth/ILS/loginfields.phtml -->
