<?php

  // Set up standard record scripts:
  $this->headScript()->appendFile("record.js");
  $this->headScript()->appendFile("check_save_statuses.js");
  // Activate Syndetics Plus if necessary:
  if ($this->syndeticsPlus()->isActive()) {
    $this->headScript()->appendFile($this->syndeticsPlus()->getScript());
  }

  // Add RDF header link if applicable:
  if ($this->export()->recordSupportsFormat($this->driver, 'RDF')) {
    $this->headLink()->appendAlternate($this->recordLink()->getActionUrl($this->driver, 'RDF'), 'application/rdf+xml', 'RDF Representation');
  }

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li>' . $this->searchMemory()->getLastSearchLink($this->transEsc('Search'), '', '</li> ') .
    '<li class="active" aria-current="page">' . $this->recordLink()->getBreadcrumb($this->driver) . '</li> ';
  $this->layout()->title = $this->driver->getShortTitle();
?>
 <?php 
// TOJSDO Remove
 $holdingTitleHold = $this->driver->tryMethod('getRealTimeTitleHold');
 //echo $this->recordLinker()->getRequestUrl($hmac->generate('gurka','generate')) . $hmac;  

// TOJSDO
//  $holdings = $this->driver->getRealTimeHoldings();
// $tab = 'holding';
//        try {
//            echo $this->context($this)->renderInContext(
//                'RecordTab/holdingsils/standard.phtml',
//                ['holding' => reset($holdings['holdings'] )["items"][0]]
//            );
//        } catch (Exception $e) {
//            echo $this->context($this)->renderInContext(
//                'RecordTab/holdingsils/standard.phtml',
//                reset($holdings['holdings'] )["items"][0]
//            );
//        }
//
//

      
    ?>

<?php if (isset($this->scrollData) && ($this->scrollData['previousRecord'] || $this->scrollData['nextRecord'])): ?>
  <?=$this->render('record/prev-next.phtml'); ?>
<?php endif; ?>

<?=$this->record($this->driver)->getToolbar()?>

<div class="record source<?=$this->escapeHtmlAttr($this->driver->getSourceIdentifier())?>">
  <?php $sidebarList = $this->related()->getList($this->driver); ?>
  <div class="<?=$this->layoutClass('mainbody')?><?=count($sidebarList) < 1 ? ' solo' : '' ?>">
    <input type="hidden" value="<?=$this->escapeHtmlAttr($this->driver->getUniqueId())?>" class="hiddenId" />
    <input type="hidden" value="<?=$this->escapeHtmlAttr($this->driver->getSourceIdentifier()) ?>" class="hiddenSource" />
    <?=$this->flashmessages()?>
    <?=$this->record($this->driver)->getCoreMetadata()?>

    <script>
        function _swith(name) {
             if (name=="holdings"){
               $("#holdings").removeClass("initiallyActive");
               $("#versions").removeClass("active");
               $("#details").removeClass("active");
               $("#holdings").addClass("active");
               $("#versions").addClass("initiallyActive");
               $("#details").addClass("initiallyActive");
               $("#toc").addClass("initiallyActive");
             }
             if (name=="details"){
               $("#details").removeClass("initiallyActive");
               $("#versions").removeClass("active");
               $("#holdings").removeClass("active");
               $("#details").addClass("active");
               $("#versions").addClass("initiallyActive");
               $("#holdings").addClass("initiallyActive");
               $("#toc").addClass("initiallyActive");
             }
             if (name=="versions"){
               $("#versions").removeClass("initiallyActive");
               $("#holdings").removeClass("active");
               $("#details").removeClass("active");
               $("#versions").addClass("active");
               $("#holdings").addClass("initiallyActive");
               $("#details").addClass("initiallyActive");
               $("#toc").addClass("initiallyActive");
             }
             if (name=="toc"){
               $("#toc").removeClass("initiallyActive");
               $("#versions").removeClass("active");
               $("#holdings").removeClass("active");
               $("#details").removeClass("active");
               $("#toc").addClass("active");
               $("#version").addClass("initiallyActive");
               $("#holdings").addClass("initiallyActive");
               $("#details").addClass("initiallyActive");
             }
             console.log('name: ',name);
             //$("a").css({"background-color":"","color":""});
             //$("a.active").css({"background-color":"white","color":"black"});
             console.log("[monk] url hash js: ",window.location.hash);
             //if (!window.location.hash) { console.clear(); }
        }
    </script>
    <style>
     a.active:active { color: red !importan; }
    </style>


    <?php if (count($this->tabs) > 0): ?>
      <a name="tabnav"></a>
      <div class="record-tabs">
        <ul class="nav nav-tabs">
          <?php foreach ($this->tabs as $tab => $obj): ?>
            <?php // add current tab to breadcrumbs if applicable:
              $desc = $obj->getDescription();
              $tabName = preg_replace("/\W/", "-", strtolower($tab));
              $tabClasses = [ 'record-tab', $tabName ];
              //echo "w: ".$tabName;
              //echo "u: ".$_SERVER['REQUEST_URI'];
              //echo "f: ".mb_stripos($_SERVER['REQUEST_URI'],$tabName);
              if (0 === strcasecmp($this->activeTab, $tab)) {
                if (!$this->loadInitialTabWithAjax || !$obj->supportsAjax()) {
                  //$tabClasses[] = 'active';
                }
                $tabClasses[] = 'initiallyActive';
                $this->layout()->breadcrumbs .= '<li class="active">' . $this->transEsc($desc) . '</li>';
                $activeTabObj = $obj;
              }
              if (!$obj->isVisible()) { $tabClasses[] = 'hidden'; }
              if (!$obj->supportsAjax()) { $tabClasses[] = 'noajax'; }
            ?>
            <li class="<?=implode(' ', $tabClasses)?>" id="<?=$tabName?>" data-tab="<?=$tabName?>"<?php if ($obj->supportsAjax() && in_array($tab, $this->backgroundTabs)):?> data-background<?php endif ?>>
              <a onclick="_swith('<?=$tabName?>')" href="<?=$this->recordLink()->getTabUrl($this->driver, $tab)?>"><?=$this->transEsc($desc)?></a>
	    </li>
          <?php endforeach; ?>
        </ul>

        <div class="tab-content">
          <?php if (!$this->loadInitialTabWithAjax || !isset($activeTabObj) || !$activeTabObj->supportsAjax()): ?>
            <div class="tab-pane active <?=$this->escapeHtmlAttr($this->activeTab) ?>-tab">
              <?=isset($activeTabObj) ? $this->record($this->driver)->getTab($activeTabObj) : '' ?>
            </div>
          <?php endif; ?>
        </div>
      </div>
    <?php endif; ?>

    <?=$this->driver->supportsCoinsOpenURL()?'<span class="Z3988" title="' . $this->escapeHtmlAttr($this->driver->getCoinsOpenURL()) . '"></span>':''?>
  </div>

  <div class="<?=$this->layoutClass('sidebar')?>">
    <?php foreach ($sidebarList as $current): ?>
      <?=$this->related()->render($current)?>
    <?php endforeach; ?>
  </div>
</div>
<?=$this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, '$(document).ready(recordDocReady);', 'SET'); ?>

