<?php foreach ($data as $field): ?>
  <?php /* Depending on the record driver, $field may either be an array with
     "name" and "number" keys or a flat string containing only the series
     name.  We should account for both cases to maximize compatibility. */ ?>
  <?php if (is_array($field)): ?>
    <?php if (!empty($field['name'])): ?>
        <?=$this->escapeHtml($field['name'])?>
      <?php if (!empty($field['number'])): ?>
        <?=$this->escapeHtml($field['number'])?><?= $this->transEsc('PostSeriesNumber') == "PostSeriesNumber" ? "" : $this->transEsc('PostSeriesNumber') ?>
      <?php endif; ?>
      <br/>
    <?php endif; ?>
  <?php else: ?>
    <a href="<?=$this->record($this->driver)->getLink('series', $field)?>"><?=$this->escapeHtml($field)?></a><br/>
  <?php endif; ?>
<?php endforeach; ?>
