<!-- START ./RecordDriver/DefaultRecord/format-list.phtml -->
<?php foreach ($this->driver->getFormats() as $format): ?>
  <?php if ($translated = $this->transEsc($format)): ?>
    <?=$this->transEscAttr('data_format_prep')?>&nbsp<span class="format <?=$this->record($this->driver)->getFormatClass($format) ?>"><?=$translated ?></span>
  <?php endif; ?>
<?php endforeach; ?>
<!-- STOP ./RecordDriver/DefaultRecord/format-list.phtml -->
