<?php
  $user = $this->auth()->isLoggedIn();
  $patron = $user ? $this->auth()->getILSPatron() : false;
  $capabilityParams = $patron ? ['patron' => $patron] : [];
  $ilsOnline = ('ils-none' !== $this->ils()->getOfflineMode());

  $config = $this->config()->get('LOTS');
  $lots_show_fines = $config->UserMenu->showFinesMenu ?? false;
?>
<button class="close-offcanvas btn btn-link" data-toggle="offcanvas"><?=$this->transEsc('navigate_back') ?></button>
<h3><?=$this->transEsc('Your Account')?></h3>
<div class="myresearch-menu account-menu">
  <?php if ($ilsOnline && $this->ils()->checkCapability('getMyTransactions', $capabilityParams)): ?>
    <a href="<?=$this->url('myresearch-checkedout')?>" class="btn btn-primary btn-block btn-sm text-left<?=$this->active == 'checkedout' ? ' active' : ''?>">
      <span class="flex-col"><i class="fa fa-fw fa-book" aria-hidden="true"></i>&nbsp;<?=$this->transEsc('Checked Out Items')?></span>
      <span class="checkedout-status status hidden"><i class="fa fa-spin fa-spinner" aria-hidden="true"></i></span>
    </a>
  <?php endif; ?>
  <?php if ($ilsOnline && $this->ils()->checkFunction('getMyTransactionHistory', $capabilityParams)): ?>
    <a href="<?=$this->url('myresearch-historicloans')?>"<?=$this->active == 'historicloans' ? ' class="flex checkedout btn btn-primary btn-block btn-sm text-left active"' : ''?>>
      <i class="fa fa-fw fa-history" aria-hidden="true"></i> <?=$this->transEsc('Loan History')?>
    </a>
  <?php endif; ?>
  <?php if ($ilsOnline && $this->ils()->checkCapability('getMyHolds', $capabilityParams)): ?>
    <a href="<?=$this->url('myresearch-holds')?>" class="flex checkedout btn btn-primary btn-block btn-sm text-left <?=$this->active == 'holds' ? ' active' : ''?>">
      <span class="flex-col"><i class="fa fa-fw fa-flag" aria-hidden="true"></i>&nbsp;<?=$this->transEsc('Holds and Recalls')?></span>
      <span class="holds-status status hidden"><i class="fa fa-spin fa-spinner" aria-hidden="true"></i></span>
    </a>
  <?php endif; ?>

  <?php if ($ilsOnline && $this->ils()->checkFunction('ILLRequests', $capabilityParams)): ?>
    <a href="<?=$this->url('myresearch-illrequests')?>" class="flex checkedout btn btn-primary btn-block btn-sm text-left<?=$this->active == 'ILLRequests' ? ' active' : ''?>">
      <span class="flex-col"><i class="fa fa-fw fa-exchange" aria-hidden="true"></i> <?=$this->transEsc('Interlibrary Loan Requests')?></span>
      <span class="illrequests-status status hidden"><i class="fa fa-spin fa-spinner" aria-hidden="true"></i></span>
    </a>
  <?php endif; ?>
<!-- LOTS show media-->
  <?php if ($lots_show_fines && $ilsOnline && $this->ils()->checkCapability('getMyFines', $capabilityParams)): ?>
    <a href="<?=$this->url('myresearch-fines')?>" class="flex checkedout btn btn-primary btn-block btn-sm text-left<?=$this->active == 'fines' ? ' active' : ''?>">
      <span class="flex-col"><i class="fa fa-fw fa-usd" aria-hidden="true"></i>&nbsp;<?=$this->transEsc('Fines')?></span>
      <span class="fines-status status hidden"><i class="fa fa-spin fa-spinner" aria-hidden="true"></i></span>
    </a>
  <?php endif; ?>
  <a href="<?=$this->url('myresearch-profile')?>" class="flex checkedout btn btn-primary btn-block btn-sm text-left<?=$this->active == 'profile' ? ' active' : ''?>">
    <i class="fa fa-fw fa-user" aria-hidden="true"></i> <?=$this->transEsc('Profile')?>
  </a>
  <?php if ($ilsOnline && $user && $user->libraryCardsEnabled()): ?>
  <a href="<?=$this->url('librarycards-home')?>" class="flex checkedout btn btn-primary btn-block btn-sm text-left<?=$this->active == 'librarycards' ? ' active' : ''?>">
      <i class="fa fa-fw fa-barcode" aria-hidden="true"></i> <?=$this->transEsc('Library Cards')?>
    </a>
  <?php endif; ?>
  <?php if ($this->overdrive()->showMyContentLink()):?>
  <a href="<?=$this->url('overdrive-mycontent')?>" class="flex checkedout btn btn-primary btn-block btn-sm text-left<?=$this->active == 'dgcontent' ? ' active' : ''?>">
      <i class="fa fa-fw fa-download" aria-hidden="true"></i> <?=$this->transEsc('Overdrive Content')?>
    </a>
  <?php endif; ?>
  <?php if ($this->accountCapabilities()->getSavedSearchSetting() === 'enabled'): ?>
  <a href="<?=$this->url('search-history')?>" class="flex checkedout btn btn-primary btn-block btn-sm text-left<?=$this->active == 'history' ? ' active' : ''?>">
      <i class="fa fa-fw fa-search" aria-hidden="true"></i> <?=$this->transEsc('history_saved_searches')?>
    </a>
  <?php endif; ?>
  <?php if ($user): ?>
    <a href="<?=$this->url('myresearch-logout')?>" class="flex checkedout btn btn-primary btn-block btn-sm text-left" >
      <i class="fa fa-fw fa-sign-out" aria-hidden="true"></i> <?=$this->transEsc("Log Out")?>
    </a>
  <?php endif; ?>
</div>

<?php if ($user && $this->userlist()->getMode() !== 'disabled'): ?>
  <h3><?=$this->transEsc('Your Lists')?></h3>
  <div class="myresearch-menu">
  <a href="<?=$this->url('myresearch-favorites')?>" class="flex checkedout btn btn-primary btn-block btn-sm text-left<?=$this->active == 'favorites' ? ' active' : ''?>">
      <i class="fa fa-fw fa-star" aria-hidden="true"></i> <?=$this->transEsc('Your Favorites')?>
    </a>
    <?php $lists = $user->getLists() ?>
    <?php foreach ($lists as $list): ?>
      <a href="<?=$this->url('userList', ['id' => $list['id']])?>"<?=$this->active == 'list' . $list['id'] ? ' class="btn btn-primary btn-block btn-sm text-left active"' : 'class="btn btn-primary btn-block btn-sm text-left"'?>>
        <?=$this->escapeHtml($list['title'])?>
        <span class="badge"><?=$list->cnt ?></span>
      </a>
    <?php endforeach; ?>
    <a href="<?=$this->url('editList', ['id' => 'NEW'])?>" class="btn btn-primary btn-block btn-sm text-left">
      <i class="fa fa-fw fa-plus" aria-hidden="true"></i> <?=$this->transEsc('Create a List') ?>
    </a>
  </div>
<?php endif ?>
