<?php
  $config = $this->config()->get('LOTS');
  $AllowHistoryConfiguration = $config->History->allowConfiguration;

    // Set up page title:
    $this->headTitle($this->translate('My Profile'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Profile') . '</li>';

    // Template for use by the renderArray helper:
    $arrTemplate = '<tr><th>%%LABEL%%:</th><td> %%VALUE%%</td></tr>';
    $user = $this->auth()->isLoggedIn();
    $patron = $user ? $this->auth()->getILSPatron() : false;
    $capabilityParams = $patron ? ['patron' => $patron] : [];
    $updatePhone = $this->ils()->checkFunction('updatePhone', $capabilityParams);
    $updateSmsNumber = $this->ils()->checkFunction('updateSmsNumber', $capabilityParams);
    $updateMobileNumber = $this->ils()->checkFunction('updateMobileNumber', $capabilityParams);
    if ($AllowHistoryConfiguration) {
        $updateLoanHistory = $this->ils()->checkFunction('updateTransactionHistoryState', $capabilityParams);
        if (isset($updateLoanHistory['options'])) {
            $updateLoanHistory = $updateLoanHistory['options'];
        }
    }
?>

<a class="search-filter-toggle visible-xs" href="#myresearch-sidebar" data-toggle="offcanvas" title="Expand Sidebar">
  <?=$this->transEsc('Your Account') ?>
</a>

<div class="<?=$this->layoutClass('mainbody')?>">
  <h2><?=$this->transEsc('Your Profile')?></h2>
  <?=$this->flashmessages();?>

  <table class="table table-striped">
    <form id="profile_form" class="form-inline" method="post">
    <?=
      $this->renderArray(
          $arrTemplate,
          $this->user,
          [
              $this->transEsc('First Name') => 'firstname',
              $this->transEsc('Last Name') => 'lastname',
              $this->transEsc('Email') => 'email',
          ]
      );
    ?>
    <?php /* this section renders under two distinct circumstances; see if/else below: */ ?>
    <?php if (count($this->pickup ?? []) > 1 || !empty($this->preferredLibraryDisplay)): ?>
      <tr>
        <th><?=$this->transEsc('Preferred Library')?>:</th>
        <td>
          <?php if (count($this->pickup ?? []) > 1): // case 1: set home library allowed?>
            <?php
              $selected = (strlen($this->profile['home_library'] ?? '') > 0)
                ? $this->profile['home_library'] : $this->defaultPickupLocation
            ?>
              <select id="home_library" name="home_library" class="form-control flex-grow-1">
                <?php foreach ($this->pickup as $lib): ?>
                  <option value="<?=$this->escapeHtmlAttr($lib['locationID'])?>"<?=($selected == $lib['locationID']) ? ' selected="selected"' : ''?>><?=$this->transEscWithPrefix('location_', $lib['locationDisplay'])?></option>
                <?php endforeach; ?>
              </select>
          <?php else: // case 2: set home library disallowed, but default provided by ILS?>
            <?=$this->transEscWithPrefix('location_', $this->preferredLibraryDisplay)?>
          <?php endif; ?>
        </td>
      </tr>
    <?php endif; ?>
    <?php /* this section renders under two distinct circumstances; see if/else below: */ ?>
    <?php if (isset($updateLoanHistory) && isset($this->profile['loan_history'])) {  ?>
      <tr>
        <th><?=$this->transEsc('Save history')?>:</th>
        <td>
            <?php
              $selected = $this->profile['loan_history'];
            ?>
              <select id="loan_history" name="loan_history" class="form-control flex-grow-1">
                <?php foreach ($updateLoanHistory as $id => $name): ?>
                  <option value="<?=$this->escapeHtmlAttr($id)?>"<?=($selected == $id) ? ' selected="selected"' : ''?>><?=$this->transEsc($name)?></option>
                <?php endforeach; ?>
              </select>
        </td>
      </tr>
    <?php } ?>
            <?php if (!empty($this->profile['phone']) || $updatePhone): ?>
              <?php if ($updatePhone): ?>
      <tr>
        <th><?=$this->transEsc('Phone')?>:</th>
        <td>
              <input type="tel" name="profile_tel" class="form-control flex-grow-1"
              value="<?=empty($this->profile['phone']) ? '' : $this->escapeHtmlAttr($this->profile['phone']) ?>" 
              title="<?=$this->transEscAttr('Phone') ?>" />
              <?php else: ?>
                <div class="my-profile-col profile-title"><?=$this->transEsc('Phone') ?>:</div>
                <div class="profile-text-value"><?=$this->escapeHtml($this->profile['phone']) ?></div>
              <?php endif; ?>
</td>
</tr>

        <?php if (!empty($this->profile['mobile_phone']) || $updateMobileNumber): ?>
             <?php if ($updateMobileNumber): ?>
                <tr>
                <th><?=$this->transEsc('Mobile Number')?>:</th>
                <td>
                <input class="form-control flex-grow-1" type="tel" name="profile_mobile_number" value="<?=empty($this->profile['mobile_phone']) ? '' : $this->escapeHtmlAttr($this->profile['mobile_phone']) ?>" title="<?=$this->transEscAttr('Mobile Number') ?>" />
             <?php else: ?>
                <div class="my-profile-col profile-title"><?=$this->transEsc('Mobile Number') ?>:</div>
                <div class="profile-text-value"><?=$this->escapeHtml($this->profile['mobile_phone']) ?></div>
             <?php endif; ?>
             </td>
             </tr>
        <?php endif; ?>

        <?php if (!empty($this->profile['sms_number']) || $updateSmsNumber): ?>
            <?php if ($updateSmsNumber): ?>
                <tr>
                <th><?=$this->transEsc('SMS Number')?>:</th>
                <td>
                <input class="form-control flex-grow-1" type="tel" name="profile_sms_number" value="<?=empty($this->profile['sms_number']) ? '' : $this->escapeHtmlAttr($this->profile['sms_number']) ?>" title="<?=$this->transEscAttr('SMS Number') ?>" />
            <?php else: ?>
                <div class="my-profile-col profile-title"><?=$this->transEsc('SMS Number') ?>:</div>
                <div class="profile-text-value"><?=$this->escapeHtml($this->profile['sms_number']) ?></div>
            <?php endif; ?>
            </td>
            </tr>
        <?php endif; ?>

<tr>
        <td>
        </td>
        <td>
            <div class="my-profile-row" align="right">
              <?php if ($updatePhone): ?>
                <input id="save-library-profile" name="saveLibraryProfile" type="submit" value="<?=$this->transEscAttr("save_my_profile") ?>" 
                  class="btn btn-primary my-profile-btn" />
              <?php endif; ?>
              <div class="clearfix"></div>
            </div>
</td>
</tr>

          </form>
  </table>
  <div id="account-actions">
    <?php if ($this->auth()->getManager()->supportsEmailChange()): ?>
      <a class="btn btn-default" href="<?=$this->url('myresearch-changeemail') ?>">
        <i class="fa fa-fw fa-envelope" aria-hidden="true"></i> <?=$this->transEsc('Change Email Address') ?>
      </a>
    <?php endif; ?>

    <?php if ($this->auth()->getManager()->supportsPasswordChange()): ?>
      <a class="btn btn-default" href="<?=$this->url('myresearch-changepassword') ?>">
        <i class="fa fa-fw fa-lock" aria-hidden="true"></i> <?=$this->transEsc('Change Password') ?>
      </a>
    <?php endif; ?>

    <?php if ($this->accountDeletion): ?>
      <a class="btn btn-default" href="<?=$this->url('myresearch-deleteaccount') ?>" data-lightbox>
        <i class="fa fa-times"></i> <?=$this->transEsc('delete_account_title') ?>
      </a>
    <?php endif; ?>
  </div>

  <?php if (is_array($this->profile)): ?>
    <h3><?=$this->transEsc('Library Catalog Profile')?></h3>
    <p>
      <?=$this->context($this)->renderInContext('librarycards/selectcard.phtml', ['user' => $this->user]); ?>
    </p>
    <table class="table table-striped">
      <?=
        $this->renderArray(
            $arrTemplate,
            $this->profile,
            [
              $this->transEsc('First Name') => 'firstname',
              $this->transEsc('Last Name') => 'lastname',
              $this->transEsc('Address') . ' 1' => 'address1',
              $this->transEsc('Address') . ' 2' => 'address2',
              $this->transEsc('Zip') => 'zip',
              $this->transEsc('City') => 'city',
              $this->transEsc('Country') => 'country',
              $this->transEsc('Phone Number') => 'phone',
              $this->transEsc('Mobile Number') => 'mobile_phone',
              $this->transEsc('Group') => 'group',
              $this->transEsc('patron_account_expires') => 'expiration_date'
            ]
        );
      ?>
    </table>
  <?php elseif ('ils-none' !== $this->ils()->getOfflineMode() && $this->patronLoginView && !empty($this->patronLoginView->getTemplate())): ?>
    <?=$this->partial($this->patronLoginView);?>
  <?php endif; ?>
</div>

<div class="<?=$this->layoutClass('sidebar')?>" id="myresearch-sidebar">
  <?=$this->context($this)->renderInContext("myresearch/menu.phtml", ['active' => 'profile'])?>
</div>
